name: CI

# Controls when the workflow will run
on:
  
  push:
    branches: [ "main" ]
    paths:
      - 'Pipeline/Phishing/Production/read_file.py'
      - 'Pipeline/Phishing/Production/train_op.py'
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      
      - name: Install dependencies
        working-directory: ./Pipeline/Phishing/Production
        run: pip install -r main_requirements.txt

      - name: Check condition
        working-directory: ./Pipeline/Phishing/Production
        run: python check_condition.py

      - name: Run read
        working-directory: ./Pipeline/Phishing/Production
        run: python read_file.py

      
      - name: Run train
        working-directory: ./Pipeline/Phishing/Production 
        run: python train_op.py

      - name: Install dependencies
        working-directory: ./Pipeline/Phishing/Production
        run: pip install -r compile_requirements.txt

      - name: Run compile
        working-directory: ./Pipeline/Phishing/Production
        env:
          KUBEFLOW_USERNAME: ${{ secrets.USER }}
          KUBEFLOW_PASSWORD: ${{ secrets.PASSWORD }}
          KUBEFLOW_TOKEN: ${{ secrets.TOKEN }}
        run: python compile.py 
