name: run-python-script
run-name: ${{ github.actor }} is running test.py

on:
  push:
    branches:
      - actions_test

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      
      - name: Run CI.py
        run: python CI.py
